#!/usr/bin/env bash

RED="\e[0;31m"
YELLOW="\e[0;33m"
GREEN="\e[0;32m"
RESET="\e[0;0m"

output="Pof gjti Uxp gjti Uisff gjti"

total=0
test_passed=0

langs=("C" "Go" "Python")

cmd=(
    "gcc ../c/main.c -o c_main && ./c_main text.txt out.txt 1"
    "go build ../go/main.go && ./main text.txt out.txt 1"
    "../python/main.py text.txt out.txt 1"
)

echo -e "${GREEN}=============================================${RESET}"
echo -e "${RED}                  TESTS: \e[0;0m"
echo -e "${GREEN}=============================================${RESET}"

for ((i = 0; i < 3; i++)); do

    echo -e "\n${GREEN}---------------------------------------------${RESET}"
    echo -e ">>${YELLOW} ${langs[i]} language.${RESET}"
    echo -e "${GREEN}---------------------------------------------${RESET}\n"

    outtxt=$(<out.txt)
    total=$((total + 1))
    rm out.txt
    eval ${cmd[$i]}

    if [[ $outtxt == $output ]]; then
        echo -e "Test ${GREEN}Passed!${RESET}"
        test_passed=$((test_passed + 1))
    else
        echo -e "Test ${RED}Failed!${RESET}"
    fi
done

echo -e "\n\n${GREEN}=============================================${RESET}"
echo -e "Total tests: ${YELLOW}$total${RESET}"
echo -e "Passed tests: ${GREEN}$test_passed${RESET}"
echo -e "Failed tests: ${RED}$(($total - $test_passed))${RESET}"
echo -e "${GREEN}=============================================${RESET}"
