#!/usr/bin/env bash

RED="\e[0;31m"
YELLOW="\e[0;33m"
GREEN="\e[0;32m"
RESET="\e[0;0m"

path=""
key=
input_file=""

if [[ "$#" != 1 ]]; then
    printf "Usage: $0 <caesar|custom>\n"
    exit 1
fi

if [[ "$1" == "caesar" ]]; then
    output="Pof gjti Uxp gjti Uisff gjti"
    path="caesar"
    key=1
    input_file="caesar"
elif [[ "$1" == "custom" ]]; then
    output="Lmv urhs Gdl urhs Gsivv urhs"
    path="custom_key"
    input_file="custom"
else
    printf "Invalid option\n"
fi

total=0
test_passed=0

langs=("C" "Go" "Lua" "Python")

cmd=(
    "gcc ../${path}/c/main.c -o main && ./main $input_file.txt out.txt $key"
    "go build ../${path}/go/main.go && ./main $input_file.txt out.txt $key"
    "../${path}/lua/main.lua $input_file.txt out.txt $key"
    "../${path}/python/main.py $input_file.txt out.txt $key"
)

printf "${GREEN}=============================================${RESET}\n"
printf "${RED}                  TESTS: \e[0;0m\n"
printf "${GREEN}=============================================${RESET}\n"

for ((i = 0; i < ${#cmd[@]}; i++)); do

    printf "\n${GREEN}---------------------------------------------${RESET}\n"
    printf ">>${YELLOW} ${langs[i]} language.${RESET}\n"
    printf "${GREEN}---------------------------------------------${RESET}\n\n"

    rm out.txt
    eval ${cmd[i]}
    outtxt=$(<out.txt)
    total=$((total + 1))

    if [[ $outtxt == $output ]]; then
        printf "Test ${GREEN}Passed!${RESET}\n"
        test_passed=$((test_passed + 1))
    else
        printf "Test ${RED}Failed!${RESET}\n"
    fi
done

printf "\n\n${GREEN}=============================================${RESET}\n"
printf "Total tests: ${YELLOW}$total${RESET}\n"
printf "Passed tests: ${GREEN}$test_passed${RESET}\n"
printf "Failed tests: ${RED}$(($total - $test_passed))${RESET}\n"
printf "${GREEN}=============================================${RESET}\n"
